Repository ITCompetition-Mediger/Mediger-frontend, pull requests merged in 2022-09, with the labels that each got.

#16 0901 header
  src/App.js
  src/components/Header.js
  src/pages/Home.js
Labels: 🌸UI, 🔨Task

#18 NavBar Component 생성
  src/components/NavBar.js
Labels: 🌸UI, 🔨Task

#17 Search Component 생성
  package-lock.json
  package.json
  src/components/SearchBar.js
  src/images/Search.png
Labels: 🌸UI, 🔨Task

#23 Modal Component 추가
  src/components/AddModal.js
  src/components/RemoveModal.js
Labels: 🌸UI, 🔨Task

#21 의약품 검색 페이지 UI 추가
  src/images/pillImage.png
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic

#19 Mediger List Component 생성
  src/App.js
  src/components/Header.js
  src/components/Medicine.js
  src/components/MedigerListStyle.js
  src/pages/MedigerList.js
  src/pages/medigerList/MedigerList.js
Labels: 🌸UI, 🔨Task, ⚒Epic

#40 지도 페이지 UI 설계
  src/pages/map/HospitalList.js
  src/pages/map/HospitalListPage.js
  src/pages/map/HospitalMapPage.js
  src/pages/map/PharmacyList.js
  src/pages/map/PharmacyListPage.js
  src/pages/map/PharmacyMapPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic

#41 App.js에 React Router 적용
  src/App.js
Labels: ⚒Epic, ♻️Refactor, ✨Feature

#25 의약품 검색 페이지 UI 변경
  src/components/NavBar.js
  src/components/SearchBar.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#42 NavBar에 React Router 적용
  src/components/NavBar.js
Labels: 🔨Task, ✨Feature

#45 로그인 페이지 UI 설계
  src/pages/login/LoginButton.js
  src/pages/login/LoginPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#43 마이페이지 UI 설계
  package-lock.json
  package.json
  src/App.js
  src/components/Mediger.js
  src/components/NavBar.js
  src/pages/Home.js
  src/pages/myMediger/AddToMediger.js
  src/pages/myMediger/DailyMediger.js
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ✨Feature

#47 Develop 브랜치에서 Main 브랜치로 병합
  package-lock.json
  package.json
  src/App.js
  src/components/AddModal.js
  src/components/Header.js
  src/components/Medicine.js
  src/components/Mediger.js
  src/components/NavBar.js
  src/components/RemoveModal.js
  src/components/SearchBar.js
  src/images/Search.png
  src/images/pillImage.png
  src/pages/Home.js
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/LoginPage.js
  src/pages/login/NaverLoginButton.js
  src/pages/map/HospitalList.js
  src/pages/map/HospitalListPage.js
  src/pages/map/HospitalMapPage.js
  src/pages/map/PharmacyList.js
  src/pages/map/PharmacyListPage.js
  src/pages/map/PharmacyMapPage.js
  src/pages/medigerList/MedigerList.js
  src/pages/myMediger/AddToMediger.js
  src/pages/myMediger/DailyMediger.js
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚙️Setting

#50 프론트엔드 배포
  .github/workflows/npm-publish.yml
  src/App.js
  src/components/NavBar.js
  src/pages/myMediger/AddToMediger.js
Labels: 😚Distribution

#52 Develop 브랜치에서 main 브랜치로 병합
  .github/workflows/npm-publish.yml
  src/App.js
  src/components/NavBar.js
  src/pages/myMediger/AddToMediger.js
Labels: ⚙️Setting, 😚Distribution

#53 프론트엔드 배포 오류 수정
  src/components/Medicine.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚒Epic, ♻️Refactor, 😚Distribution

#54 Develop 브랜치에서 main 브랜치로 병합
  src/components/Medicine.js
  src/components/NavBar.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚙️Setting, ⚒Epic, ♻️Refactor, 😚Distribution

#55 프론트엔드 배포 설정
  .github/workflows/npm-publish.yml
Labels: 😚Distribution

#56 Develop 브랜치에서 main 브랜치로 병합
  .github/workflows/npm-publish.yml
Labels: ⚙️Setting, 😚Distribution

#57 프론트엔드 배포 오류 수정
  .github/workflows/npm-publish.yml
  package.json
Labels: ⚙️Setting, ♻️Refactor, 😚Distribution

#58 Develop 브랜치에서 main 브랜치로 병합
  .github/workflows/npm-publish.yml
  package.json
Labels: 🐞BugFix, ⚙️Setting, 😚Distribution

#59 의약품 검색 페이지 UI 수정
  src/components/SearchBar.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#60 로그인 페이지 UI 수정
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/NaverLoginButton.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#61 Develop 브랜치에서 main 브랜치로 병합
  src/components/SearchBar.js
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/NaverLoginButton.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🐞BugFix, ⚙️Setting, ⚒Epic, ♻️Refactor

#62 React Responsive Component 생성
  package.json
  src/components/ReactResponsive.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ⚒Epic

#63 의약품 검색 UI에 React Responsive 적용
  src/components/SearchBar.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ⚒Epic, ♻️Refactor

#64 Develop브랜치에서 Main 브랜치로 병합
  package.json
  src/components/ReactResponsive.js
  src/components/SearchBar.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚙️Setting, 😚Distribution

#65 의약품 검색 페이지 UI에 React Responsive 수정
  src/components/NavBar.js
  src/components/SearchBar.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ⚒Epic, ♻️Refactor

#67 지도 페이지 UI에 React Responsive 적용
  src/components/NavBar.js
  src/pages/map/HospitalList.js
  src/pages/map/HospitalListPage.js
  src/pages/map/PharmacyList.js
  src/pages/map/PharmacyListPage.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ⚒Epic, ♻️Refactor

#68 Develop 브랜치에서 Main 브랜치로 병합
  src/components/NavBar.js
  src/components/SearchBar.js
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/LoginPage.js
  src/pages/login/NaverLoginButton.js
  src/pages/map/HospitalList.js
  src/pages/map/HospitalListPage.js
  src/pages/map/PharmacyList.js
  src/pages/map/PharmacyListPage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
Labels: ⚙️Setting, 😚Distribution

#69 SearchBar Component 수정
  src/components/NavBar.js
  src/components/SearchBar.js
Labels: 🌸UI, 🔨Task, ♻️Refactor

#70 Develop 브랜치에서 Main 브랜치로 병합
  src/components/NavBar.js
  src/components/SearchBar.js
Labels: ⚙️Setting, 😚Distribution

#71 BugFix: NavBar Component에서 React Router 경로 수정
  src/components/NavBar.js
Labels: 🐞BugFix, ⚙️Setting, 😚Distribution

#72 지도 페이지 UI React Responsive 수정
  src/components/NavBar.js
  src/pages/map/HospitalListPage.js
  src/pages/map/PharmacyListPage.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ♻️Refactor

#73 Developg 브랜치에서 Main 브랜치로 병합
  src/pages/map/HospitalListPage.js
  src/pages/map/PharmacyListPage.js
Labels: 🖥Responsive Web, ⚒Epic, ♻️Refactor, 😚Distribution

#74 의약품 검색 페이지 수정
  src/components/NavBar.js
  src/components/StyledModal.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor, ✨Feature

#48 Mypage에서 AddToMediger Component 생성
  package-lock.json
  package.json
  src/components/DailyMedigerIconWidget.js
  src/components/DailyMedigerWidget.js
  src/components/MedigerListWidget.js
  src/components/NavBar.js
  src/components/StyledModal.js
  src/pages/Home.js
  src/pages/myMediger/MonthlyCalender.css
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#75 Develop브랜치에서 Main브랜치로 병합[Netlify]
  package-lock.json
  package.json
  src/components/AddModal.js
  src/components/DailyMedigerIconWidget.js
  src/components/DailyMedigerWidget.js
  src/components/MedigerListWidget.js
  src/components/NavBar.js
  src/components/StyledModal.js
  src/pages/Home.js
  src/pages/myMediger/MonthlyCalender.css
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚙️Setting, ♻️Refactor, 😚Distribution

#78 Develop브랜치에서 Main브랜치로 병합[Netlify]
  src/App.js
  src/components/NavBar.js
  src/pages/myMediger/Mypage.js
Labels: ⚙️Setting, ♻️Refactor, 😚Distribution

#81 Edit
  src/components/Header.js
  src/components/Layout.js
  src/components/Medicine.js
  src/components/Mediger.js
  src/components/MypageLayout.js
  src/components/NavBar.js
  src/components/SearchBar.js
  src/components/StyledModal.js
  src/pages/Home.js
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/LoginPage.js
  src/pages/login/NaverLoginButton.js
  src/pages/medigerList/MedigerList.js
  src/pages/myMediger/AddToMediger.js
  src/pages/myMediger/DailyMediger.js
  src/pages/myMediger/MonthlyCalender.css
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🖥Responsive Web, 🔨Task, ⚒Epic, ♻️Refactor, ✨Feature

#82 Develop브랜치에서 Main브랜치로 병합[Netlify]
  src/components/Header.js
  src/components/Layout.js
  src/components/Medicine.js
  src/components/Mediger.js
  src/components/MypageLayout.js
  src/components/NavBar.js
  src/components/SearchBar.js
  src/components/StyledModal.js
  src/pages/Home.js
  src/pages/login/GoogleLoginButton.js
  src/pages/login/KakaoLoginButton.js
  src/pages/login/LoginButton.js
  src/pages/login/LoginHeader.js
  src/pages/login/LoginPage.js
  src/pages/login/NaverLoginButton.js
  src/pages/medigerList/MedigerList.js
  src/pages/myMediger/AddToMediger.js
  src/pages/myMediger/DailyMediger.js
  src/pages/myMediger/MonthlyCalender.css
  src/pages/myMediger/MonthlyMediger.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchList.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, ⚙️Setting, 🖥Responsive Web, ⚒Epic, ♻️Refactor, 😚Distribution

#83 각 페이지 UI에 데스크탑 뷰 적용
  src/components/DailyMedigerIconWidget.js
  src/components/DailyMedigerWidget.js
  src/components/DesktopView.js
  src/components/MedigerListWidget.js
  src/components/TabletView.js
  src/pages/login/LoginPage.js
  src/pages/map/HospitalListPage.js
  src/pages/map/HospitalMapPage.js
  src/pages/map/PharmacyListPage.js
  src/pages/map/PharmacyMapPage.js
  src/pages/medigerList/MedigerList.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: 🌸UI, 🖥Responsive Web, ⚒Epic, ♻️Refactor

#84 Develop브랜치에서 Main브랜치로 병합[Netlify]
  src/components/DailyMedigerIconWidget.js
  src/components/DailyMedigerWidget.js
  src/components/DesktopView.js
  src/components/MedigerListWidget.js
  src/components/TabletView.js
  src/pages/login/LoginPage.js
  src/pages/map/HospitalListPage.js
  src/pages/map/HospitalMapPage.js
  src/pages/map/PharmacyListPage.js
  src/pages/map/PharmacyMapPage.js
  src/pages/medigerList/MedigerList.js
  src/pages/myMediger/Mypage.js
  src/pages/pillSearch/PillSearchPage.js
  src/pages/pillSearch/PillSearchPlusPage.js
Labels: ⚙️Setting, 🖥Responsive Web, 😚Distribution

#87 지도 API Component 생성
  public/index.html
  src/pages/map/HospitalMapAPI.js
  src/pages/map/PharmacyMapAPI.js
  src/pages/map/PharmacyMapPage.js
Labels: 🖥Responsive Web, 🔨Task, ⚒Epic, ♻️Refactor, ✨Feature, 🖥API

#88 Develop브랜치에서 Main브랜치로 병합[Netlify]
  public/index.html
  src/pages/map/HospitalMapAPI.js
  src/pages/map/PharmacyMapAPI.js
  src/pages/map/PharmacyMapPage.js
Labels: ⚙️Setting, 🖥Responsive Web, ♻️Refactor, 😚Distribution

#89 Refactor: 소스 코드 정리
  public/index.html
  src/pages/map/PharmacyMapAPI.js
Labels: ⚒Epic, ♻️Refactor, ✨Feature

#90 Develop브랜치를 Main브랜치로 병합[Netlify]
  public/index.html
  src/pages/map/PharmacyMapAPI.js
Labels: ⚙️Setting, 😚Distribution

#91 Mediger Logo
  src/components/Header.js
  src/images/Logo1.png
  src/images/Logo2.png
  src/pages/Home.js
  src/pages/login/LoginHeader.js
Labels: 🌸UI, 🔨Task, ⚒Epic, ♻️Refactor

#92 Develop브랜치에서 Main브랜치로 병합[Netlify]
  src/components/Header.js
  src/images/Logo1.png
  src/images/Logo2.png
  src/pages/Home.js
  src/pages/login/LoginHeader.js
Labels: ⚙️Setting, ♻️Refactor, 😚Distribution
